version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel_api
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: angular_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: laravel_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: